---
# IP address for OpenConrail (e.g. 192.168.0.2)
contrail_ip:

# Gateway address for OpenConrail (e.g. 192.168.0.1)
contrail_gateway:

# Interface name for OpenConrail (e.g. eth0)
contrail_interface:


# IP address for Openstack VM (e.g. 192.168.0.3)
openstack_ip:

# [Optional] If not specified default value 8082 will be used.
#contrail_port: 8082

# [Required] Openstack branch used on VMs.
openstack_branch: stable/ocata
# [Required] OpenContrail branch to build on VM.
contrail_branch:

# If true, then install networking_bgpvpn plugin with contrail driver
install_networking_bgpvpn_plugin: false
